CREATE DATABASE university_db;
USE university_db;

SET FOREIGN_KEY_CHECKS = 0;

-- BASE PERSON

CREATE TABLE Person (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  dni VARCHAR(20) UNIQUE NOT NULL,
  email VARCHAR(100),
  phone VARCHAR(20)
);

-- UNIVERSITY STRUCTURE

CREATE TABLE University (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL
);

CREATE TABLE Faculty (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  university_id INT NOT NULL,
  FOREIGN KEY (university_id) REFERENCES University(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Career (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  faculty_id INT NOT NULL,
  FOREIGN KEY (faculty_id) REFERENCES Faculty(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Program (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  career_id INT NOT NULL,
  FOREIGN KEY (career_id) REFERENCES Career(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- TIME STRUCTURE

CREATE TABLE AcademicYear (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year INT NOT NULL
);

CREATE TABLE Semester (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  academic_year_id INT NOT NULL,
  FOREIGN KEY (academic_year_id) REFERENCES AcademicYear(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- COURSES

CREATE TABLE Course (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  credits INT NOT NULL,
  program_id INT NOT NULL,
  FOREIGN KEY (program_id) REFERENCES Program(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- PEOPLE ROLES

CREATE TABLE Student (
  id INT AUTO_INCREMENT PRIMARY KEY,
  person_id INT UNIQUE NOT NULL,
  enrollment_date DATE NOT NULL,
  career_id INT NOT NULL,
  FOREIGN KEY (person_id) REFERENCES Person(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (career_id) REFERENCES Career(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE Professor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  person_id INT UNIQUE NOT NULL,
  hire_date DATE NOT NULL,
  faculty_id INT NOT NULL,
  FOREIGN KEY (person_id) REFERENCES Person(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (faculty_id) REFERENCES Faculty(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- COURSE ASSIGNMENT (N:M)

CREATE TABLE CourseProfessor (
  course_id INT,
  professor_id INT,
  PRIMARY KEY (course_id, professor_id),
  FOREIGN KEY (course_id) REFERENCES Course(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (professor_id) REFERENCES Professor(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- ENROLLMENT (N:M)

CREATE TABLE Enrollment (
  student_id INT,
  course_id INT,
  semester_id INT,
  PRIMARY KEY (student_id, course_id, semester_id),
  FOREIGN KEY (student_id) REFERENCES Student(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (course_id) REFERENCES Course(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (semester_id) REFERENCES Semester(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- EVALUATION

CREATE TABLE Exam (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  semester_id INT NOT NULL,
  exam_date DATE NOT NULL,
  FOREIGN KEY (course_id) REFERENCES Course(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (semester_id) REFERENCES Semester(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Grade (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  exam_id INT NOT NULL,
  grade DECIMAL(5,2) NOT NULL,
  FOREIGN KEY (student_id) REFERENCES Student(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (exam_id) REFERENCES Exam(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;